const propertyData = {
    user: {
        user_id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        password: "hashed_password",
        date_of_birth: "1990-05-15",
        img_url: "https://example.com/user-profile.jpg",
        address: "123 Elm Street, Springfield, USA",
    },
    house: {
        house_id: 1,
        title: "Modern Family Home",
        description: "A beautiful, fully-furnished modern home located in the heart of the city.",
        full_address: "456 Oak Avenue, Springfield, USA",
        city : "Springfield",
        country: "USA",
        state: "Illinois",
        zip: "62704",
        longitude: -89.6501,
        latitude: 39.7817,
        user_id: 1,
    },
    house_details: {
        house_details_id: 1,
        type: "Single Family",
        status: "For Sale",
        size: 2000,
        bedrooms: 3,
        bathrooms: 2,
        rooms: 6,
        year_built: 2016,
        house_id: 1,
    },
    amenities: {
        amenities_id: 1,
        air_condition: true,
        cable_tv: true,
        elevator: false,
        wifi: true,
        pet_friendly: true,
        furnished: true,
        garden: true,
        swimming_pool: false,
        intercom: true,
        disabled_access: false,
        fireplace: true,
        garage: true,
        heating: true,
        security: true,
        parking: true,
        house_id: 1,
    },
    prices: {
        price_id: 1,
        price: 350000.0,
        before_price_label: null,
        after_price_label: null,
        house_id: 1,
    },
    images: {
        image_id: 1,
        links: [
            "https://i.ibb.co/BVfrbWm/6dc6af95-1c15-40dd-af1d-8ec57847ddc4.jpg",
            "https://i.ibb.co/Ry9Q9Nq/38a0287d-22bc-45b8-bf03-8360e9b8f16b.jpg",
            "https://i.ibb.co/mJYMYmD/697653ee-42f1-473f-98a3-995d4f906cb7.jpg",
            "https://i.ibb.co/RS9GynM/aaf62b40-7cc7-4ab3-8832-953d570cca44.jpg",
            "https://i.ibb.co/s5vvJ6t/f93f8d33-ba89-4512-bedb-5f2970ba211a.jpg",
        ],
        house_id: 1,
    },
};

export default propertyData;
